Hide sign out button from users until the log in.
Vero-Ventures/transaction-classification-bot pull request #63
Opened 2024-05-21 19:49 UTC by BRogers-BCIT

Simple fix that adds a use state to the sign out button to hide from users who have not logged in. 
Button is hidden by default and checks the session status before updating to be seen.

2024-05-21 22:45 UTC, shawnbirring requested changes
I don't think you need a state for this, you can just use a if statement to check if there is a session, and then conditionally render the button or just nothing

2024-05-21 23:10 UTC, BRogers-BCIT commented
> I don't think you need a state for this, you can just use a if statement to check if there is a session, and then conditionally render the button or just nothing

Checking the session is asynch but rendering components are synchronous so some form of callback is required for when the session is retrieved. Direct comparison will either always fail or not work entirely because a promise is returned by getSession.

 Using a use state for the className to update the CSS and show the button is just the simplest implementation of a callback. It is simpler to just show a hidden button when the callback resolves, instead of trying to add in a whole new element.

2024-05-22 17:06 UTC, BRogers-BCIT commented
Trying a different method for now.

2024-05-22 17:49 UTC, shawnbirring approved these changes

2024-05-22 17:52 UTC, merged